import Head from "next/head";
import Image from "next/image";
import Input from "../components/Input";
import { signOut } from "next-auth/react";
import { NextPageContext } from "next";
import { getSession } from "next-auth/react";
import useCurrentUser from "../hooks/useCurrentUser"

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/auth",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
}

export default function Home() {
  const {data: user} = useCurrentUser();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl underline bold text-green-500">Netflix CLone</h1>
      <p className="text-white">Logged in as: {user?.name}</p>
      <button className="h-10 w-full bg-white" onClick={() => signOut()}>
        Sign Out
      </button>
    </>
  );
}
